#SPDX-License-Identifier: MIT-0
---
# tasks file for web

- name: Install Apache2 package and PHP Support Ubuntu
  tags: apache, apache2, ubuntu
  apt:
    name: 
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu" # for Ubuntu

- name: Install Apache2 package and PHP Support CentOS
  tags: apache, centos, httpd
  dnf:
    name: 
      - httpd
      - php
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS" # for CentOS

- name: start httpd (CentOS)
  tags: apache, centos, httpd
  service:
    name: httpd
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"

- name: "Print Confirm if Successful"
  debug:
    msg: "Apache and PHP are installed and running successfully."