---
- hosts: linuxservers
  become: true
  tasks:

  - name: Install Apache and PHP for Debian Ubuntu & Red Hat/CentOS
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes


    # - name: Install Apache2 package and PHP Support Ubuntu
    #   apt:
    #     name: 
    #       - apache2
    #       - libapache2-mod-php
    #     state: latest
    #     update_cache: yes
    #   when: ansible_distribution == "Ubuntu" # for Ubuntu

    # - name: Install Apache2 package and PHP Support CentOS
    #   dnf:
    #     name: 
    #       - httpd
    #       - php
    #     state: latest
    #     update_cache: yes
    #   when: ansible_distribution == "CentOS" # for CentOSS