---
# PRE-TASKS: UPDATE AND UPGRADE
- name: Install and Deploy Prometheus
  hosts: web_servers
  become: true

  roles:
    - prometheus

# [CentOS]: sudo dnf check-update && sudo dnf upgrade -y
- name: Update repository cache and upgrade packages (CentOS / RHEL)
  tags: always
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
    update_only: true
  when: ansible_os_family == "RedHat"

# [Ubuntu]: sudo apt update && sudo apt dist-upgrade -y
- name: Update repository cache and upgrade packages (Ubuntu / Debian)
  tags: always
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  when: ansible_os_family == "Debian"

# [Ubuntu]: sudo apt install -y wget tar curl
# [CentOS]: sudo dnf install -y wget tar curl

- name: Install utilities (wget, tar, curl)
  ansible.builtin.package:
    name:
      - wget 
      - tar
      - curl
    state: present

# TASK 2: CREATE THE PROMETHEUS USER

# [Ubuntu/CentOS]: sudo groupadd --system prometheus
- name: Create prometheus system group
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    state: present
    system: true


# [Ubuntu]: sudo useradd --system --no-create-home --shell /bin/false -g prometheus prometheus
# [CentOS]: sudo useradd --system --no-create-home --shell /sbin/nologin -g prometheus prometheus
# [Verification]: id prometheus
- name: Create prometheus system user with disabled login shell
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    shell: "{{ '/bin/false' if ansible_os_family == 'Debian' else '/sbin/nologin' }}"
    create_home: false
    system: true
    state: present
  

# TASK 3: CREATE PROMETHEUS DIRECTORIES

# [Ubuntu/CentOS]: sudo mkdir -p /etc/prometheus
- name: Create configuration directory /etc/prometheus
  ansible.builtin.file:
    path: "{{ prometheus_config_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'

# [Ubuntu/CentOS]: sudo mkdir -p /var/lib/prometheus
# [Verification]: ls -ld /etc/prometheus /var/lib/prometheus
- name: Create data directory /var/lib/prometheus
  ansible.builtin.file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'
