#SPDX-License-Identifier: MIT-0
---
# tasks file for elk_stack
- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Include CentOS specific tasks
  ansible.builtin.include_tasks: centos.yml
  when: ansible_os_family == "RedHat"

- name: Include common ELK configuration tasks
  ansible.builtin.include_tasks: common.yml