---
- name: Create a directory
  hosts: web_servers
  tasks:
    - name: Create ansible-directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/ansible-directory"
        state: directory